#!/bin/bash
gpio mode 8 IN
gpio mode 9 IN
gpio mode 0 IN
gpio mode 2 OUT
gpio mode 30 OUT
gpio mode 21 OUT
gpio mode 22 OUT
gpio mode 23 OUT
gpio mode 24 OUT
gpio mode 25 OUT
gpio mode 1 OUT
gpio mode 4 OUT
gpio mode 5 OUT
gpio mode 6 OUT
gpio mode 10 IN
gpio mode 31 IN
gpio mode 26 IN
gpio mode 27 OUT
gpio mode 28 OUT
gpio mode 29 OUT
